### ISSUE TITLE
Question about the bit-width of outputs of int1 Tensor Core

### ISSUE THREAD

**Issue by HaoKun-Li** [BoyuanFeng/APNN-TC#2]
Hello, thanks for your wonderful work and available code! However, during read this paper, I have the following questions.
 
In the paper, the authors claim that "the int1 Tensor Core compute primitive can only generate 32 outputs". It seems that 32 bit-width output is relatively large for Int1 matric multiply-accumulate (MMA). So I want to check whether we can control the bit-width of outputs for Int1 MMA.

First, I try to access the white paper in reference [32] https://www.nvidia.com/content/dam/en-zz/Solutions/Data-Center/nvidia-amperearchitecture-whitepaper.pdf but I got an error with "Even AI can't find this page!". 

Then, I access https://www.nvidia.com/content/PDF/[nvidia-ampere-ga-102-gpu-architecture-whitepaper-v2.pdf](https://www.nvidia.com/content/PDF/nvidia-ampere-ga-102-gpu-architecture-whitepaper-v2.pdf) to search relative information in this white paper. However, I still can not find the introduction about the setting of Tensor Core outputs' bitwidth.

So, my question is:
(1) Where can I find the description that can support or provide evidence for  "the int1 Tensor Core compute primitive can only generate 32 outputs" in white papers or other documents? 
(2) Do I have any way to control the outputs' bit-width of the int1 Tensor Core compute? 

Looking forward to your reply.
Best wish to you！

**Comment by BoyuanFeng** [comment]
Nvidia may have deprecated these two links. Please check this doc instead: https://docs.nvidia.com/cuda/ampere-tuning-guide/index.html

**Comment by HaoKun-Li** [comment]
> Nvidia may have deprecated these two links. Please check this doc instead: https://docs.nvidia.com/cuda/ampere-tuning-guide/index.html

Thanks very much！
